apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-pod-port-forward
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-pod-port-forward
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  resourceNames: ["hashicorp-packer"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  resourceNames: ["hashicorp-packer"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-pod-port-forward
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-pod-port-forward
subjects:
  - kind: ServiceAccount
    name: my-pod-port-forward
    namespace: default