apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: runner
  namespace: actions-runner-system
spec:
  ephemeral: false
  replicas: 4
  repository: SophosPOCAutomation/Sophos_POC_Automation_Project
  selector:
    matchLabels:
      app: runner
  serviceName: runner
  template:
    spec:
      containers:
      - name: runner
        env: []
        ports:
        - name: http
          containerPort: 8080
    metadata:
      labels:
        name: vsphere-packer-builds
        app: runner

---
apiVersion: v1
kind: Service
metadata:
  name: runner
  namespace: actions-runner-system
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: runner
  type: LoadBalancer