---
- include_vars: '../../../vars/github_actions_vars.yaml'

- name: Create actions-runner-system namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: '{{ KUBECONFIG }}'
    definition: 
      apiVersion: v1
      kind: Namespace
      metadata:
        name: actions-runner-system
        labels:
          app: actions-runner-system

- name: Create controller manager secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: '{{ KUBECONFIG }}'
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: controller-manager
        namespace: actions-runner-system
      type: Opaque
      data: 
        github_app_id: '{{ APP_ID | b64encode }}'
        github_app_installation_id: '{{ INSTALLATION_ID | b64encode }}'
        github_app_private_key: "{{ lookup('file', '{{ PRIVATE_KEY_FILE_PATH }}') | b64encode}}"