apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
  namespace: actions-runner-system
  labels:
    app: runner
spec:
  selector:
    matchLabels:
      app: runner
  replicas: 2
  template:
    spec:
      repository: RalphBrynard/vsphere-packer-builds