apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
    name: poc
    namespace: default
spec:
    replicas: 2
    template:
        spec:
            organization: SophosPOCAutomation
