---
smallstep_enrollment_token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic21hbGxzdGVwIiwiaXNzIjoia3ViZXJuZXRlcy9zZXJ2aWNlYWNjb3VudCIsInN1YiI6InNtYWxsc3RlcCIsImlhdCI6MTY0NzIwMDc5OX0.1FB96A6golfkSMH-Q1bRsj1mSLZqOyyco4K4t_vluWeLyZ0gD17qVvNr3RmOaYjfKVnQza__3Y8u7qvfH7okOA
team_id: thebrynards