---
# ./vars/name_vars.yml
realm: ${realm}
realm_domain: ${realm_domain}
realm_domain_server: ${realm_domain_server}
kerberos_user: ${kerberos_user}
kerberos_user_password: ${kerberos_user_password}
realm_ad_ou: ${realm_ad_ou}
sssd_testuser: ${sssd_testuser}
krb5_server: ${krb5_server}
krb5_realm: ${krb5_realm}
ldap_uri: ${ldap_uri}
ldap_default_bind_dn: ${ldap_default_bind_dn}
ldap_default_authtok: ${ldap_default_authtok}
ldap_default_authtok_type: ${ldap_default_authtok_type}
ldap_search_base: ${ldap_search_base}
ldap_user_search_base: ${ldap_user_search_base}
ldap_user_object_class: ${ldap_user_object_class}
ldap_user_gecos: ${ldap_user_gecos}
ldap_group_search_base: ${ldap_group_search_base}
ldap_group_object_class: ${ldap_group_object_class}
ldap_user_name: ${ldap_user_name}
ldap_user_principal: ${ldap_user_principal}
ldap_group_name: ${ldap_group_name}
ldap_user_objectsid: ${ldap_user_objectsid}
ldap_group_objectsid: ${ldap_group_objectsid}
ldap_user_primary_group: ${ldap_user_primary_group}
time_server: ${time_server}
smallstep_enrollment_token: ${smallstep_enrollment_token}
team_id: ${team_id}