---
- hosts: masters
  gather_facts: true
  connection: local
  vars:
    KUBECONFIG: ../.kube/config
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    PRIVATE_KEY_FILE: "{{ lookup('file','{{ PRIVATE_KEY_FILE_PATH }}') }}"
  vars_files:
    - "../vars/github_actions_vars.yaml"

  tasks:
        
    - name: Get cert-manager and actions-runner-controller definitions
      get_url:
        url: "{{ item }}"
        dest: ../manifests/remote/
        mode: '0664'
      loop:
        - "https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.yaml"
        - "https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.22.0/actions-runner-controller.yaml"

    - name: Deploy cert-manager and actions-runner-controller
      k8s:
        kubeconfig: '{{ KUBECONFIG }}'
        src: '{{ item }}'
        state: present
      loop:
        - '../manifests/remote/cert-manager.yaml'
        - '../manifests/remote/actions-runner-controller.yaml'

    - name: Create Generic Secret
      kubernetes.core.k8s:
        state: present
        kubeconfig: '{{ KUBECONFIG }}'
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            name: controller-manager
            namespace: actions-runner-system
          type: Opaque
          data:
            github_app_id: '{{ APP_ID | b64encode }}'
            github_app_installation_id: '{{ INSTALLATION_ID | b64encode }}'
            github_app_private_key: '{{ PRIVATE_KEY_FILE | b64encode }}'