---
- hosts: masters
  gather_facts: true
  connection: local
  vars:
    KUBECONFIG: ../.kube/config
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  
  roles:
    - githubactions.controller
    

