---
- hosts: masters
  gather_facts: true
  connection: local
  vars:
    KUBECONFIG: ../.kube/config
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    runner_name: poc
    owner: SophosPOCAutomation
    deploy_runner: true
    deploy_runner_deployment: true

  roles:
    - githubactions.runner
    - metallb.loadbalancer