---
- hosts: masters
  gather_facts: true
  connection: local
  vars:
    KUBECONFIG: ../.kube/config
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    runner_name: poc-runner
    owner: SophosPOCAutomation
    repo_name: Sophos_POC_Automation_Project
    deploy_runner: true
    create_bare_metal_loadbalancer: true

  roles:
    - githubactions.runner
    - metallb.loadbalancer