---
- hosts: masters
  gather_facts: true
  connection: local
  vars:
    KUBECONFIG: ../.kube/config
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:

    - name: Deploy NGINX app
      kubernetes.core.k8s:
        kubeconfig: '{{ KUBECONFIG }}'
        src: ../kubernetes/nginxlb.yaml
        state: present