apiVersion: v1
kind: Service
metadata:
    name: packer
    namespace: actions-runner-system
    annotations:
        metallb.universe.tf/address-pool: default
    spec:
        ports:
        - port: 8000
          targetPort: 8000
        - port: 8001
          targetPort: 8001
        - port: 8002
          targetPort: 8002
        - port: 8003
          targetPort: 8003
        - port: 8004
          targetPort: 8004
        - port: 8005
          targetPort: 8005
        - port: 8006
          targetPort: 8006
        - port: 8007
          targetPort: 8007
        - port: 8008
          targetPort: 8008
        - port: 8009
          targetPort: 8009
        - port: 8010
          targetPort: 8010
        - port: 8011
          targetPort: 8011
        - port: 8012
          targetPort: 8012
        - port: 8013
          targetPort: 8013
        - port: 8014
          targetPort: 8014
        - port: 8015
          targetPort: 8015
        - port: 8016
          targetPort: 8016
        - port: 8017
          targetPort: 8017
        - port: 8018
          targetPort: 8018
        - port: 8019
          targetPort: 8019
        - port: 8020
          targetPort: 8020
        - port: 8021
          targetPort: 8021
        - port: 8022
          targetPort: 8022
        - port: 8023
          targetPort: 8023
        - port: 8024
          targetPort: 8024
        - port: 8025
          targetPort: 8025
        - port: 8026
          targetPort: 8026
        - port: 8027
          targetPort: 8027
        - port: 8028
          targetPort: 8028
        - port: 8029
          targetPort: 8029
        - port: 8030
          targetPort: 8030
        - port: 8031
          targetPort: 8031
        - port: 8032
          targetPort: 8032
        - port: 8033
          targetPort: 8033
        - port: 8034
          targetPort: 8034
        - port: 8035
          targetPort: 8035
        - port: 8036
          targetPort: 8036
        - port: 8037
          targetPort: 8037
        - port: 8038
          targetPort: 8038
        - port: 8039
          targetPort: 8039
        - port: 8040
          targetPort: 8040
        - port: 8041
          targetPort: 8041
        - port: 8042
          targetPort: 8042
        - port: 8043
          targetPort: 8043
        - port: 8044
          targetPort: 8044
        - port: 8045
          targetPort: 8045
        - port: 8046
          targetPort: 8046
        - port: 8047
          targetPort: 8047
        - port: 8048
          targetPort: 8048
        - port: 8049
          targetPort: 8049
        - port: 8050
          targetPort: 8050
        selector:
            app: github
        type: LoadBalancer
